export const GAME_STATE = Object.freeze({
    STARTUP: "STARTUP",
    LOADING_RESOURCES: "LOADING_RESOURCES",
    STARTUP_COMPLETE: "STARTUP_COMPLETE",
    LEVEL_STARTING: "LEVEL_STARTING",
    PLAYING: "PLAYING",
    PAUSED: "PAUSED",
    LEVEL_RESTARTING: "LEVEL_RESTARTING",
    GAME_ENDING: "ENDING",
    GAME_OVER: "GAME_OVER",
});
